### ISSUE TITLE
Broken Clojure 1.5 support: intentional?

### ISSUE THREAD

**Issue by ptaoussanis** [AvisoNovate/pretty#35]
Hi Howard,

Just a heads-up that ` [io.aviso/pretty "0.1.18"]` supported Clojure 1.5 but `[io.aviso/pretty "0.1.19"]` seems not to.

One break is here (there may be more): https://github.com/AvisoNovate/pretty/blame/master/src/io/aviso/columns.clj#L189

`some?` was only added in Clojure 1.6.

Was dropping Clojure 1.5 support intentional?

Thanks a lot, cheers :-)

**Comment by ptaoussanis** [comment]
Update: excuse me, this seems to have come from as far back as 0.1.17

**Comment by hlship** [comment]
No, it was not intentional and there's no reason for it ... though I pretty live in Clojure 1.7 now.
