### ISSUE TITLE
Documentation page has no documentation

### ISSUE THREAD

**Issue by mullr** [AvisoNovate/pretty#36]
The "Full Documentation" link in the readme goes to https://portal.aviso.io/#/docs/open-source, which displays nought but a pretty picture.

**Comment by pmoriarty** [comment]
Which browser are you using? Site is currently broken in Firefox and Safari. Sorry about inconvenience but Chrome will work.

**Comment by mullr** [comment]
Ah, I was using chrome canary, where it is broken as well.

**Comment by hlship** [comment]
This has been resolved with the new documentation at readthedocs.org.
