### ISSUE TITLE
Tailing log files with pretty stacktraces

### ISSUE THREAD

**Issue by dluksza** [AvisoNovate/pretty#52]
Pretty is awesome when it is used from repl, but when exception is logged into log file readability drops down. Color markers like `#033[33m` are polluting the output. 

Is there any way to tail log files with pretty formatting and colors?

**Comment by hlship** [comment]
You could write a filter to strip out the ANSI escape codes, I'll work out how to best do that and add some docs.

**Comment by hlship** [comment]
Generally, when logging to a file, you want to bind `*fonts*` to nil.

**Comment by hlship** [comment]
When using `less`, the -R flag should help

       -R or --RAW-CONTROL-CHARS
              Like  -r,  but  only ANSI "color" escape sequences are output in
              "raw" form.  Unlike -r, the screen appearance is maintained cor-
              rectly  in  most  cases.   ANSI  "color"  escape  sequences  are
              sequences of the form:

                   ESC [ ... m

              where the "..." is zero or more color  specification  characters
              For  the  purpose  of  keeping  track of screen appearance, ANSI
              color escape sequences are assumed to not move the cursor.   You
              can  make less think that characters other than "m" can end ANSI
              color escape  sequences  by  setting  the  environment  variable
              LESSANSIENDCHARS to the list of characters which can end a color
              escape sequence.  And you can make less  think  that  characters
              other  than the standard ones may appear between the ESC and the
              m by setting the environment variable  LESSANSIMIDCHARS  to  the
              list of characters which can appear.

And there's this: http://www.commandlinefu.com/commands/view/3584/remove-color-codes-special-characters-with-sed
