### ISSUE TITLE
Highlight app namespaces

### ISSUE THREAD

**Issue by danielcompton** [AvisoNovate/pretty#60]
It seems like it would be handy to be able to highlight my own app's namespaces when printing the exception, perhaps by bolding it? This is quite a common feature in exception reporters, where you can provide a namespace/package prefix to match on.

This could possibly be made into a frame rule, with a new frame visibility of `:bold`?

**Comment by hlship** [comment]
Seems like a good idea.

**Comment by rymndhng** [comment]
I would love this idea 😁
