### ISSUE TITLE
Pretty exceptions in terminal window?

### ISSUE THREAD

**Issue by brjann** [AvisoNovate/pretty#65]
I'm developing a ring app and uncaught exceptions in the app are output to the terminal window running the lein session. I can't figure out how to use pretty to format these exceptions in addition to the REPL exceptions. I've tried adding `(pretty-repl/install-pretty-exceptions)` and `(pretty-logging/install-uncaught-exception-handler)` to my outermost middleware but nothing works. 

Any suggestions?

**Comment by hlship** [comment]
I would look into what Ring middleware is running; there's a standard bit of Ring middleware for reporting exceptions that you could replace with something that builds on Pretty instead.
