### ISSUE TITLE
Implicit middleware found

### ISSUE THREAD

**Issue by ccann** [AvisoNovate/pretty#68]
When I specify `[io.aviso/pretty "0.1.36"]` as a plugin for my project and run a lein command I get

```
Warning: implicit middleware found: pretty.plugin/middleware
Please declare all middleware in :middleware as implicit loading is deprecated.
Unable to enable pretty exception reporting, as io.aviso/pretty is not a project dependency.
```
Clojure 1.10
Leiningen 2.8.3

**Comment by hlship** [comment]
I think this will be a documentation change, to note that you must add Pretty as middleware.  I'll start looking into this, I'm still on Lein 2.7.1.
